apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-gitops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/dhuriyapawan/TerraformAWS.git
    targetRevision: main
    path: helm/node-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true